### PR TITLE
#2 updated test containers version, scala version, scala test version an…

### PR DESCRIPTION
**Pull request by devsprint**
…d ContainerSpec to update it to use new mockito api from scala test.

I've done updates of the libraries, compile works fine, the unit test (ContainerSpec) could not be started. I never used gradle before, so it could be because of the version of it or something else.

### CODE REVIEW

**Comment by dimafeng** [comment]
@devsprint Thank you! I'll take a look and merge tonight

**Comment by devsprint** [comment]
@dimafeng thanks for fast reply. I'm intending to use it as soon as it is ready. My project is using scala 2.12 and that's main reason why I requested this change. My intention is to write few integration tests with elasticsearch running in container.

**Comment by dimafeng** [comment]
@devsprint one of the test failed. If you could solve it, this may simplify the merging process.
https://travis-ci.org/dimafeng/testcontainers-scala/builds/185821369

**Comment by devsprint** [comment]
@dimafeng fixed

**Comment by dimafeng** [comment]
@devsprint Thank you! I'll prepare the project to be published both for 2.11 and 2.12. I hope it'll be done tonight.

**Comment by devsprint** [comment]
@dimafeng thanks!

**Pull request merged**
